@startuml

skinparam {
    state {
        BackgroundColor #f0f0f0
        BorderColor #000000
        FontSize 16
        FontStyle bold
        Style uml2
        ArrowColor #cc7832
        ArrowFontColor #A9B7C6
        ArrowFontStyle bold
        ArrowStyle italic
    }

    backgroundColor #3c3f41
    titleFontColor #A9B7C6
    titleFontSize 44
    packageBackgroundColor #808080-#black
    packageFontColor #cccccc

    circledCharacterFontColor f0f0f0
    circledCharacterFontSize 17
    circledCharacterFontStyle bold
    circledCharacterFontName  Courier
    circledCharacterRadius 11

    stereotypeCBackgroundColor #909090
    stereotypeABackgroundColor #CC0000
    stereotypeIBackgroundColor #0000bb

    noteBackgroundColor #808080
    noteBorderColor #black
}

state "Формирование корзины" as S1 {
    state "Выбрать книгу" as S1.1
    S1.1 : Выбирается книгу из каталога

    state "Добавить в корзину" as S1.2
    S1.2 : Выбранная книга
    S1.2 : добавляется в корзину

    [*] -right-> S1.1
    S1.1 -down-> S1.2 : Книга\n требуется
    S1.2 -down-> S1.1 : Требуются\n ещё книги
    S1.2 -right-> [*] : Больше\n книг не\n требуется
}

state "Проверка уровня доступа" as S2 {
    state "Просмотр уровня пользователя" as S2.1
    S2.1 : Проверка уровня доступа
    
    state "Отказ в доступе" as S2.2
    S2.2 : Сообщение об
    S2.2 : ошибке

    state "Разрешение доступа" as S2.3
    S2.3 : Сообщение об
    S2.3 : успешном завершении

    [*] -down-> S2.1
    S2.1 -down-> S2.2 : Уровень меньше
    S2.1 -down-> S2.3 : Уровень подходит
    S2.1 -right-> [*] : Уровень\n проверен
    S2.2 -up-> S2.1
    S2.3 -up-> S2.1
}

state "Проверка наличия в базе данных" as S3 {
    state "Проверка наличия" as S3.1
    S3.1 : Проверяется наличие
    S3.1 : товара на складе

    state "Удаление товара" as S3.2
    S3.2 : Товар удаляется
    S3.2 : из корзины

    state "Добавление товара" as S3.3
    S3.3 : Товар добавляется
    S3.3 : в накладную

    [*] -down-> S3.1
    S3.1 -down-> S3.2 : Товара нет
    S3.1 -down-> S3.3 : Товар есть
    S3.1 -right-> [*] : Все товары\n проверены
    S3.2 -up-> S3.1
    S3.3 -up-> S3.1
}

state "Оплата" as S4 {
    state "Формирование отчетности" as S4.1
    S4.1 : В документ вносятся
    S4.1 : книги из накладной

    state "Проверка наличия денег" as S4.2
    S4.2 : Производится проверка
    S4.2 : денег на карте читателя
    
    state "Отказ" as S4.3
    S4.3 : Оповещение об 
    S4.3 : отмене транзакции 

    state "Разрешение" as S4.4
    S4.4 : Оповещение об 
    S4.4 : завершении транзакции 

    state "Получение денег" as S4.5
    S4.5 : Передаётся сумма по отчетности

    [*] --> S4.1
    S4.1 --> S4.2
    S4.2 -down-> S4.3 : Недостаточно
    S4.2 -down-> S4.4 : Достаточно
    S4.3 -up->S4.2
    S4.4 -up->S4.2
    S4.4 --> S4.5
    S4.5 --> [*]
}

state "Добавление в каталог" as S5 {
    state "Добавление в каталог" as S5.1
    S5.1 : Добавление в
    S5.1 : каталог пользователя

    [*] --> S5.1
    S5.1 --> S5.1 : Есть ещё\n книги
    S5.1 --> [*] : Все книги\n добавлены
}

[*] --> S1
S1 -down-> S2 : Требуемые\n книги\n найдены
S2 -left->S3 : Уровень\n устраивает
S3 -down-> S4 : Цена\n устраивает
S3 -down-> [*] : Цена\n не устраивает
S4 -right-> S5 : Книги\n оплачены
S5 -right-> [*]


@enduml