@startuml

left to right direction

:Библиотекарь: as Man1
:Управляющий: as Man2
:Заведующий отделом: as Man3
:Читатель: as Man4

package Библиотека {
    rectangle Управление {
        (Заказ книг) as US1.1
        (Списание книг) as US1.2
    }
    rectangle Контроль {
        (Выдача) as US2.1
        (Просмотр ур. доступа) as US2.2
        (Контроль сроков) as US2.3
        (Возврат) as US2.4
 
        US2.2 ..> US2.1 : include
    }

    rectangle Каталог{
        (Просмотр ктл) as US3.1
        (Сортировка ктл) as US3.2
        (Добавление книг в ктл.) as US3.3
        (Удаление книг из ктл.) as US3.4
        (Хочет взять) as US3.5
        (Хочет отдать) as US3.6
    }
}



Man1 -- US2.1
Man1 -- US2.2

Man2 -- US1.1
Man2 -- US1.2

Man3 -- US3.3
Man3 -- US3.4

Man4 <|-- Man1

Man4 -- US3.1
Man4 -- US3.2
Man4 -- US2.3
Man4 -- US3.5
Man4 -- US3.6


US1.1 ..> US3.3 : extend
US1.2 ..> US3.4 : extend
US3.5 ..> US2.2 : include
US3.6 ..> US2.4 : include
US2.1 ..> US3.4 : extend
US2.4 ..> US3.3 : extend




@enduml