@startuml

|Накладная|
|Отчетность|
|Отдел библиотеки|



|Накладная|
start
repeat
    if (Книга есть в наличии?) then (Да)
        if (Удовлеторяет уровень доступа?) then (Да)
            :Добавить товар;
        endif   
    endif
repeat while (Не все товары добавлены)
if (Цена не устраивает?) then (Да)
else
    |Отчетность|
    :Сформировать документ;
    :Получить деньги;

    |Отдел библиотеки|
    repeat
        :Выдать книгу;
    repeat while (Не все книги выданы)
    |Накладная|
endif

stop


@enduml