@startuml

skinparam {
    class {
        BackgroundColor #f0f0f0
        BorderColor #black
        FontSize 16
        FontStyle bold
        Style uml2
        ArrowColor #cc7832
        ArrowFontColor #A9B7C6
        ArrowFontStyle bold
        ArrowStyle italic
        }

    backgroundColor #3c3f41
    titleFontColor #A9B7C6
    titleFontSize 44
    packageBackgroundColor #808080-#black
    packageFontColor #cccccc

    circledCharacterFontColor f0f0f0
    circledCharacterFontSize 17
    circledCharacterFontStyle bold
    circledCharacterFontName  Courier
    circledCharacterRadius 11

    stereotypeCBackgroundColor #909090
    stereotypeABackgroundColor #CC0000
    stereotypeIBackgroundColor #0000bb

    noteBackgroundColor #808080
    noteBorderColor #black
}

class Book {
    #int id
    #String name
    #double price
    #bool inStock
    +int getId()
    +String getName()
    +double getPrice()
    +int getQuantity()
}

class Report {
    #String name
    +errLevel()
    +errData()
}

class DataBase {
    #Map<Integer, Book> Books
    +Stock()
    +getSize()
    +Stock addItem(Item item)
    +Item getItem(Integer id)
    +Stock removeItem(Integer id)
    +Item takeItem(Integer id, int quantity)
    +Report createReport()
}

class User {
    #int id
    #string Name
    #int quantityBooksInStock
    +getLevel()
    +levelUp()
    +levelDown()
    +getBook()
    +recieveBook()
    +search()
}


class AdminPanel {
    +orderItem()
    +addItemToBd()
    +delItemFBd()
    +addUserToBd()
    +delUserFBd()
    +AdminPanel printReports()
    +List<Report> collectReports()
}


Book "1" -- "1..*" DataBase : "Содержится >"
User "1" -- "1..*" DataBase : "Содержится >"
Report "1" -- "1..*" DataBase : "Содержится >"
User ..> Book
AdminPanel ..> DataBase
AdminPanel ..> Report


@enduml